name: test-actions
on:
  push:
    branches: [master]

jobs:
  check-firebase-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install firebase-tools -g
      - run: firebase --version
  deploy-on-firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GH_ACTION_FIREBASE_HOSTING}}"
          projectId: gh-action-firebase-hosting
          channelId: live
